version: '2'

networks:
  api-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

  web-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  uploads:
    container_name: uploads
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./uploads:/usr/share/nginx/html:rw"
    working_dir: "/usr/share/nginx"
    networks:
      - web-network

  graphics:
    container_name: graphics
    build:
      context: .
      dockerfile: ./.docker/dockerfiles/graphics.dockerfile
    image: shitulv/graphics
    ports:
      - "8000:8000"
    depends_on:
      - "uploads"
    links:
      - uploads:uploads
    volumes:
      - "./uploads:/usr/app/uploads:rw"
    env_file:
      - ./.docker/env/${APP_ENV}/graphics 
    networks:
      - web-network


  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/data/db:/data/db:rw"
    networks:
      - api-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./.docker/dockerfiles/api.dockerfile
    image: shitulv/api
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb"
    networks:
      - api-network
