'use strict'

export const LIST_EVENTS_REQUEST = 'LIST_EVENTS_REQUEST'
export const LIST_EVENTS_SUCCESS = 'LIST_EVENTS_SUCCESS'
export const LIST_EVENTS_FAILURE = 'LIST_EVENTS_FAILURE'

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE'

export const CLEAR_EVENT = 'CLEAR_EVENT'