'use strict'

export const REQUEST_AREAS = 'REQUEST_AREAS'
export const LIST_AREAS_SUCCESS = 'LIST_AREAS_SUCCESS'
export const LIST_AREAS_FAILURE = 'LIST_AREAS_FAILURE'

export const REQUEST_AREA = 'REQUEST_AREA'
export const GET_AREA_SUCCESS = 'GET_AREA_SUCCESS'
export const GET_AREA_FAILURE = 'GET_AREA_FAILURE'