'use strict'

export const LIST_AREAS_REQUEST = 'LIST_AREAS_REQUEST'
export const LIST_AREAS_SUCCESS = 'LIST_AREAS_SUCCESS'
export const LIST_AREAS_FAILURE = 'LIST_AREAS_FAILURE'

export const GET_AREA_REQUEST = 'GET_AREA_REQUEST'
export const GET_AREA_SUCCESS = 'GET_AREA_SUCCESS'
export const GET_AREA_FAILURE = 'GET_AREA_FAILURE'