'user strict'

export const SEND_LIST_REQUEST = 'SEND_LIST_REQUEST'
export const LIST_COMMENTS_SUCCESS = 'LIST_COMMENTS_SUCCESS'
export const LIST_COMMENTS_FAILURE = 'LIST_COMMENTS_FAILURE'

export const SEND_CREATE_REQUEST = 'SEND_CREATE_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE'
