'user strict'

export const LIST_COMMENTS_REQUEST = 'LIST_COMMENTS_REQUEST'
export const LIST_COMMENTS_SUCCESS = 'LIST_COMMENTS_SUCCESS'
export const LIST_COMMENTS_FAILURE = 'LIST_COMMENTS_FAILURE'

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE'
