'use strict'

export const REQUEST_EVENTS = 'REQUEST_EVENTS'
export const LIST_EVENTS_SUCCESS = 'LIST_EVENTS_SUCCESS'
export const LIST_EVENTS_FAILURE = 'LIST_EVENTS_FAILURE'

export const REQUEST_EVENT = 'REQUEST_EVENT'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE'
export const CLEAR_EVENT = 'CLEAR_EVENT'

export const RESET_ORDER = 'RESET_ORDER'

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE'

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE'
