'use strict'

export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const IS_LOGGED_OUT = 'IS_LOGGED_OUT'
export const SHOW_LOGIN = 'SHOW_LOGIN'
export const HIDE_LOGIN = 'HIDE_LOGIN'

export const ENABLE_VERIFICATION = 'ENABLE_VERIFICATION'
export const DISABLE_VERIFICATION = 'DISABLE_VERIFICATION'

export const SHOW_VERIFICATION = 'SHOW_VERIFICATION'
export const HIDE_VERIFICATION = 'HIDE_VERIFICATION'

export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST'
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE'
export const RESET_VERIFICATION_ERROR = 'RESET_VERIFICATION_ERROR'

export const ENABLE_LOGIN = 'ENABLE_LOGIN'
export const DISABLE_LOGIN = 'DISABLE_LOGIN'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const UPDATE_AVATAR_URI = 'UPDATE_AVATAR_URI'

// retrieve user information
export const GET_SUCCESS = 'GET_SUCCESS'
export const GET_FAILURE = 'GET_FAILURE'

// account constants
export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'

// validate mobile number
export const SEND_MOBILE_NUMBER_FOR_VALIDATION = 'SEND_MOBILE_NUMBER_FOR_VALIDATION'
export const MOBILE_NUMBER_SAVED = 'MOBILE_NUMBER_SAVED'
export const MOBILE_NUMBER_VALIDATION_FAILED = 'MOBILE_NUMBER_VALIDATION_FAILED'

// verify mobile number
export const SEND_MOBILE_VERIFICATION_REQUEST = 'SEND_MOBILE_VERIFICATION_REQUEST'
export const MOBILE_VERIFICATION_SUCCESS = 'MOBILE_VERIFICATION_SUCCESS'
export const MOBILE_VERIFICATION_FAILURE = 'MOBILE_VERIFICATION_FAILURE'

// verify wechat account  
export const WECHAT_AUTH = 'WECHAT_AUTH'
export const SEND_WECHAT_AUTH_REQUEST = 'SEND_WECHAT_AUTH_REQUEST'
export const WECHAT_AUTH_REQUEST_SEND = 'WECHAT_AUTH_REQUEST_SEND'
export const WECHAT_USER_INFO_SUCCESS = 'WECHAT_USER_INFO_SUCCESS'
export const WECHAT_USER_INFO_FAILURE = 'WECHAT_USER_INFO_FAILURE'

export const SHOW_MOBILE_LOGIN_FORM = 'SHOW_MOBILE_LOGIN_FORM'
export const VERIFY_MOBILE_NUMBER = 'VERIFY_MOBILE_NUMBER'

//
export const CLEAR_UPDATE_ERROR = 'CLEAR_UPDATE_ERROR'