'use strict'

export const SELECT_CITY = 'SELECT_CITY'

export const NAV_TO_SIGNUP = 'NAV_TO_SIGNUP'
export const GOT_TO_SIGNUP = 'GOT_TO_SIGNUP'

export const ADD_EVENT_SIGNUP = 'ADD_EVENT_SIGNUP'
export const EVENT_SIGNUP_ADDED = 'EVENT_SIGNUP_ADDED'

export const NAV_TO_RECORD_TRAIL = 'NAV_TO_RECORD_TRAIL'
export const BACK_TO_RECORD_TRAIL = 'BACK_TO_RECORD_TRAIL'

export const NAV_TO_EDIT_TRAIL = 'NAV_TO_EDIT_TRAIL'
export const GOT_TO_EDIT_TRAIL = 'GOT_TO_EDIT_TRAIL'

export const SAVE_AGENDA = 'SAVE_AGENDA'
export const AGENDA_SAVED = 'AGENDA_SAVED'