'use strict'

export const START_RECORDING_TRAIL = 'START_RECORDING_TRAIL'
export const STOP_RECORDING_TRAIL = 'STOP_RECORDING_TRAIL'

export const STORE_PATH = 'STORE_PATH'

export const CREATE_TRAIL = 'CREATE_TRAIL'
export const EDIT_TRAIL = 'EDIT_TRAIL'
export const SET_TRAIL_POINTS = 'SET_TRAIL_POINTS'
export const SET_TRAIL_TITLE = 'SET_TRAIL_TITLE'
export const SET_TRAIL_AREAS = 'SET_TRAIL_AREAS'
export const SET_TRAIL_TYPE = 'SET_TRAIL_TYPE'
export const SET_TRAIL_DIFFICULTY = 'SET_TRAIL_DIFFICULTY'
export const SET_TRAIL_DESCRIPTION = 'SET_TRAIL_DESCRIPTION'
export const SET_TRAIL_PHOTOS = 'SET_TRAIL_PHOTOS'
export const START_CALCULATION = 'START_CALCULATION'
export const GET_TRAIL_DATA = 'GET_TRAIL_DATA'
export const SET_TO_PRIVATE = 'SET_TO_PRIVATE'
export const SET_TO_PUBLIC = 'SET_TO_PUBLIC'

export const VALIDATE_NEW_TRAIL = 'VALIDATE_NEW_TRAIL'
export const SAVE_TRAIL = 'SAVE_TRAIL'
export const SAVE_TRAIL_SUCCESS = 'SAVE_TRAIL_SUCCESS'
export const SAVE_TRAIL_FAILURE = 'SAVE_TRAIL_FAILURE'

export const RESET_TRAIL = 'RESET_TRAIL'
