'use strict'

export const START_RECORDING_TRAIL = 'START_RECORDING_TRAIL'
export const STOP_RECORDING_TRAIL = 'STOP_RECORDING_TRAIL'

export const STORE_PATH = 'STORE_PATH'

export const CREATE_TRAIL = 'CREATE_TRAIL'
export const EDIT_TRAIL = 'EDIT_TRAIL'
export const RESET_TRAIL = 'RESET_TRAIL'

export const SET_TRAIL_TITLE = 'SET_TRAIL_TITLE'
export const SET_TRAIL_AREAS = 'SET_TRAIL_AREAS'
export const SET_TRAIL_TYPE = 'SET_TRAIL_TYPE'
export const SET_TRAIL_DIFFICULTY = 'SET_TRAIL_DIFFICULTY'
export const SET_TRAIL_DESCRIPTION = 'SET_TRAIL_DESCRIPTION'
export const SET_TRAIL_PHOTOS = 'SET_TRAIL_PHOTOS'
export const SET_TO_PRIVATE = 'SET_TO_PRIVATE'
export const SET_TO_PUBLIC = 'SET_TO_PUBLIC'

export const VALIDATE_TRAIL = 'VALIDATE_TRAIL'

export const SAVE_TRAIL_REQUEST = 'SAVE_TRAIL_REQUEST'
export const SAVE_TRAIL_SUCCESS = 'SAVE_TRAIL_SUCCESS'
export const SAVE_TRAIL_FAILURE = 'SAVE_TRAIL_FAILURE'

export const UPDATE_TRAIL_REQUEST = 'UPDATE_TRAIL_REQUEST'
export const UPDATE_TRAIL_SUCCESS = 'UPDATE_TRAIL_SUCCESS'
export const UPDATE_TRAIL_FAILURE = 'UPDATE_TRAIL_FAILURE'
