'use strict'

export const RESET_ORDER = 'RESET_ORDER'
export const SET_SIGN_UPS = 'SET_SIGN_UPS'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE'

export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST'
export const LIST_ORDERS_SUCCESS = 'LIST_ORDERS_SUCCESS'
export const LIST_ORDERS_FAILURE = 'LIST_ORDERS_FAILURE'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILURE = 'GET_ORDER_SUCCESS'
