'use strict'

export const LIST_POSTS_REQUEST = 'LIST_POSTS_REQUEST'
export const LIST_POSTS_SUCCESS = 'LIST_POSTS_SUCCESS'
export const LIST_POSTS_FAILURE = 'LIST_POSTS_FAILURE'

export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAILURE = 'GET_POST_FAILURE'
