'use strict'

export const LIST_TRAILS_REQUEST = 'LIST_TRAILS_REQUEST'
export const LIST_TRAILS_SUCCESS = 'LIST_TRAILS_SUCCESS'
export const LIST_TRAILS_FAILURE = 'LIST_TRAILS_FAILURE'

export const GET_TRAIL_REQUEST = 'GET_TRAIL_REQUEST'
export const GET_TRAIL_SUCCESS = 'GET_TRAIL_SUCCESS'
export const GET_TRAIL_FAILURE = 'GET_TRAIL_FAILURE'

export const RESET_TRAIL = 'RESET_TRAIL'