'use strict'

export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const IS_LOGGED_OUT = 'IS_LOGGED_OUT'
export const SHOW_LOGIN = 'SHOW_LOGIN'
export const HIDE_LOGIN = 'HIDE_LOGIN'

export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST'
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE'
export const RESET_VERIFICATION_ERROR = 'RESET_VERIFICATION_ERROR'

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// store user information to local storage
export const STORE_USER_SUCCESS = 'STORE_USER_SUCCESS'
export const STORE_USER_FAILURE = 'STORE_USER_FAILURE'

// account constants
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

// update user avatar uri
export const UPDATE_AVATAR_URI = 'UPDATE_AVATAR_URI'

// upload mobile number
export const UPLOAD_MOBILE_REQUEST = 'UPLOAD_MOBILE_REQUEST'
export const UPLOAD_MOBILE_SUCCESS = 'UPLOAD_MOBILE_SUCCESS'
export const UPLOAD_MOBILE_FAILURE = 'UPLOAD_MOBILE_FAILURE'

// verify mobile number
export const VERIFY_MOBILE_REQUEST = 'VERIFY_MOBILE_REQUEST'
export const VERIFY_MOBILE_SUCCESS = 'VERIFY_MOBILE_SUCCESS'
export const VERIFY_MOBILE_FAILURE = 'VERIFY_MOBILE_FAILURE'

// verify wechat account
export const WECHAT_AUTH_REQUEST = 'WECHAT_AUTH_REQUEST'
export const WECHAT_AUTH_WAITING = 'WECHAT_AUTH_WAITING'
export const WECHAT_AUTH_SUCCESS = 'WECHAT_AUTH_SUCCESS'
export const WECHAT_AUTH_FAILURE = 'WECHAT_AUTH_FAILURE'
export const WECHAT_OPENID_SUCCESS = 'WECHAT_OPENID_SUCCESS'
export const WECHAT_OPENID_FAILURE = 'WECHAT_OPENID_FAILURE'

export const SHOW_MOBILE_LOGIN = 'SHOW_MOBILE_LOGIN'
export const VERIFY_MOBILE_NUMBER = 'VERIFY_MOBILE_NUMBER'

// set user photos
export const SET_USER_PHOTOS = 'SET_USER_PHOTOS'

// clear update error
export const CLEAR_UPDATE_ERROR = 'CLEAR_UPDATE_ERROR'

// set local trails
export const SET_LOCAL_TRAILS = 'SET_LOCAL_TRAILS'
