'user strict'

export const RESET_TOOLBAR = 'RESET_TOOLBAR'
export const TOOLBAR_ACTION_REQUEST = 'TOOLBAR_ACTION_REQUEST'
export const TOOLBAR_ACTION_SUCCESS = 'TOOLBAR_ACTION_SUCCESS'
export const TOOLBAR_ACTION_FAILURE = 'TOOLBAR_ACTION_FAILURE'
