'use strict'

export const REQUEST_EVENTS = 'REQUEST_EVENTS'
export const LIST_EVENTS_SUCCESS = 'LIST_EVENTS_SUCCESS'
export const LIST_EVENTS_FAILURE = 'LIST_EVENTS_FAILURE'

export const REQUEST_EVENT = 'REQUEST_EVENT'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE'

export const RESET_ORDER = 'RESET_ORDER'

export const PAY_REQUEST = 'PAY_REQUEST'
export const PAY_SUCCESS = 'PAY_SUCCESS'
export const PAY_FAILURE = 'PAY_FAILURE'
