'use strict'

export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const SHOW_LOGIN = 'SHOW_LOGIN'
export const HIDE_LOGIN = 'HIDE_LOGIN'

export const ENABLE_VERIFICATION = 'ENABLE_VERIFICATION'
export const DISABLE_VERIFICATION = 'DISABLE_VERIFICATION'

export const SHOW_VERIFICATION = 'SHOW_VERIFICATION'
export const HIDE_VERIFICATION = 'HIDE_VERIFICATION'

export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST'
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE'

export const ENABLE_LOGIN = 'ENABLE_LOGIN'
export const DISABLE_LOGIN = 'DISABLE_LOGIN'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// account constants
export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'
