'user strict'

export const RESET_TOOLBAR = 'RESET_TOOLBAR'
export const REQUEST_TOOLBAR_ACTION = 'REQUEST_TOOLBAR_ACTION'
export const TOOLBAR_ACTION_SUCCESS = 'TOOLBAR_ACTION_SUCCESS'
export const TOOLBAR_ACTION_FAILURE = 'TOOLBAR_ACTION_FAILURE'
