'use strict'

export const REQUEST_TRAILS = 'REQUEST_TRAILS'
export const LIST_TRAILS_SUCCESS = 'LIST_TRAILS_SUCCESS'
export const LIST_TRAILS_FAILURE = 'LIST_TRAILS_FAILURE'

export const REQUEST_TRAIL = 'REQUEST_TRAIL'
export const GET_TRAIL_SUCCESS = 'GET_TRAIL_SUCCESS'
export const GET_TRAIL_FAILURE = 'GET_TRAIL_FAILURE'
